"""add_role_to_user

Revision ID: 5b45c3d31cb9
Revises: 001_initial
Create Date: 2026-06-01 18:44:51.610927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b45c3d31cb9'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_email', table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.drop_index('ix_products_sku', table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.add_column('users', sa.Column('role', sa.String(length=50), server_default='user', nullable=False))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    # ### end Alembic commands ###
